"""Edit the host-owned account alias file. Example files are never modified."""

from __future__ import annotations

from pathlib import Path

from paid_media_agent.config import AccountBinding, AccountRegistry, Settings

WRITABLE_ACCOUNTS_FILE = Path("config/accounts.toml")
_HEADER = """# Account aliases map public, human-readable names to host-owned provider account ids.
# The model only ever sees the alias. Generated by `paid-media-agent accounts`; safe to edit.
"""


class AccountsFileError(ValueError):
    pass


def writable_accounts_path(root: Path) -> Path:
    return root / WRITABLE_ACCOUNTS_FILE


def active_accounts_path(settings: Settings, root: Path) -> Path:
    path = settings.paid_media_account_config_path
    return path if path.is_absolute() else root / path


def read_accounts(path: Path) -> AccountRegistry:
    if not path.exists():
        return AccountRegistry()
    return AccountRegistry.from_toml(path)


def render_accounts(registry: AccountRegistry) -> str:
    blocks = [_HEADER]
    for binding in sorted(registry.bindings, key=lambda b: b.alias):
        blocks.append(
            f'[accounts.{_toml_key(binding.alias)}]\nplatform = "{binding.platform.value}"\n'
            f'provider_account_id = "{binding.provider_account_id}"\ncurrency = "{binding.currency}"\n'
            f'timezone = "{binding.timezone}"\n'
        )
    return "\n".join(blocks)


def _toml_key(alias: str) -> str:
    return alias if alias.replace("-", "").replace("_", "").isalnum() else f'"{alias}"'


def write_accounts(path: Path, registry: AccountRegistry) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_accounts(registry), encoding="utf-8")


def add_account(
    path: Path, binding: AccountBinding, *, seed_from: Path | None = None
) -> AccountRegistry:
    """Add or replace one alias. When the target does not exist, seed it from `seed_from`."""
    registry = read_accounts(path)
    if not registry.bindings and seed_from is not None and seed_from.exists() and seed_from != path:
        registry = read_accounts(seed_from)
    for existing in registry.bindings:
        if (
            existing.alias != binding.alias
            and existing.provider_account_id == binding.provider_account_id
            and existing.platform is binding.platform
        ):
            raise AccountsFileError(f"provider account already mapped to alias {existing.alias}")
    bindings = tuple(b for b in registry.bindings if b.alias != binding.alias) + (binding,)
    updated = AccountRegistry(bindings=bindings)
    write_accounts(path, updated)
    return updated


def remove_account(path: Path, alias: str) -> AccountRegistry:
    registry = read_accounts(path)
    if registry.resolve(alias) is None:
        raise AccountsFileError(f"alias {alias} is not configured")
    updated = AccountRegistry(bindings=tuple(b for b in registry.bindings if b.alias != alias))
    write_accounts(path, updated)
    return updated
